install.packages("codetools", repos='http://cran.us.r-project.org')
install.packages("devtools", repos='http://cran.us.r-project.org')
install.packages("curl", repos='http://cran.us.r-project.org')
library(devtools)
install_github("kassambara/easyGgplot2")
install.packages("ggplot2", repos='http://cran.us.r-project.org')
install.packages("reshape", repos='http://cran.us.r-project.org')
install.packages("reshape2", repos='http://cran.us.r-project.org')
install.packages("dplyr", repos="http://R-Forge.R-project.org")
install.packages("Vennerable", repos="http://R-Forge.R-project.org")
install.packages("PerformanceAnalytics", repos="http://R-Forge.R-project.org")
install.packages("psych", repos='http://cran.us.r-project.org')
install.packages("circlize", repos='http://cran.us.r-project.org')
install.packages("corrplot", repos='http://cran.us.r-project.org')
install.packages("Hmisc", repos='http://cran.us.r-project.org')
install.packages("gdata", repos='http://cran.us.r-project.org')
source('http://bioconductor.org/biocLite.R')
biocLite()
biocLite("customProDB")
biocLite("Rsubread")
biocLite("limma")
biocLite("ComplexHeatmap")
biocLite("ConsensusClusterPlus")
